package com.example.project.model;

import java.util.Date;

public class AboutUs {

    private UserInfo create;

    private UserInfo edit;

    private UploadFile cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.img_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_about_us.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.id
     *
     * @return the value of t_about_us.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.id
     *
     * @param id the value for t_about_us.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.img_id
     *
     * @return the value of t_about_us.img_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.img_id
     *
     * @param imgId the value for t_about_us.img_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.create_user_id
     *
     * @return the value of t_about_us.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.create_user_id
     *
     * @param createUserId the value for t_about_us.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.create_date
     *
     * @return the value of t_about_us.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.create_date
     *
     * @param createDate the value for t_about_us.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.edit_user_id
     *
     * @return the value of t_about_us.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.edit_user_id
     *
     * @param editUserId the value for t_about_us.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.edit_date
     *
     * @return the value of t_about_us.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.edit_date
     *
     * @param editDate the value for t_about_us.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_about_us.content
     *
     * @return the value of t_about_us.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_about_us.content
     *
     * @param content the value for t_about_us.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    public UserInfo getCreate() {
        return create;
    }

    public void setCreate(UserInfo create) {
        this.create = create;
    }

    public UserInfo getEdit() {
        return edit;
    }

    public void setEdit(UserInfo edit) {
        this.edit = edit;
    }

    public UploadFile getCover() {
        return cover;
    }

    public void setCover(UploadFile cover) {
        this.cover = cover;
    }
}