package com.example.project.model;

import java.util.Date;

public class ArticleClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.class_name
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.class_short
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Integer classShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_class.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String dataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.id
     *
     * @return the value of t_article_class.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.id
     *
     * @param id the value for t_article_class.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.class_name
     *
     * @return the value of t_article_class.class_name
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.class_name
     *
     * @param className the value for t_article_class.class_name
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.class_short
     *
     * @return the value of t_article_class.class_short
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Integer getClassShort() {
        return classShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.class_short
     *
     * @param classShort the value for t_article_class.class_short
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setClassShort(Integer classShort) {
        this.classShort = classShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.create_user_id
     *
     * @return the value of t_article_class.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.create_user_id
     *
     * @param createUserId the value for t_article_class.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.create_date
     *
     * @return the value of t_article_class.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.create_date
     *
     * @param createDate the value for t_article_class.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.edit_user_id
     *
     * @return the value of t_article_class.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.edit_user_id
     *
     * @param editUserId the value for t_article_class.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.edit_date
     *
     * @return the value of t_article_class.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.edit_date
     *
     * @param editDate the value for t_article_class.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_class.data_type
     *
     * @return the value of t_article_class.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_class.data_type
     *
     * @param dataType the value for t_article_class.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
}