package com.example.project.model;

import java.util.Date;

public class ArticleInfo {

    private UserInfo create;

    private UserInfo edit;

    private UploadFile cover;

    private ArticleClass articleClass;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.title
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.is_top
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.class_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.img_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_info.content
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.id
     *
     * @return the value of t_article_info.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.id
     *
     * @param id the value for t_article_info.id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.title
     *
     * @return the value of t_article_info.title
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.title
     *
     * @param title the value for t_article_info.title
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.create_user_id
     *
     * @return the value of t_article_info.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.create_user_id
     *
     * @param createUserId the value for t_article_info.create_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.create_date
     *
     * @return the value of t_article_info.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.create_date
     *
     * @param createDate the value for t_article_info.create_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.is_top
     *
     * @return the value of t_article_info.is_top
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.is_top
     *
     * @param isTop the value for t_article_info.is_top
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.class_id
     *
     * @return the value of t_article_info.class_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.class_id
     *
     * @param classId the value for t_article_info.class_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.img_id
     *
     * @return the value of t_article_info.img_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.img_id
     *
     * @param imgId the value for t_article_info.img_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.edit_user_id
     *
     * @return the value of t_article_info.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.edit_user_id
     *
     * @param editUserId the value for t_article_info.edit_user_id
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.edit_date
     *
     * @return the value of t_article_info.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.edit_date
     *
     * @param editDate the value for t_article_info.edit_date
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.data_type
     *
     * @return the value of t_article_info.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.data_type
     *
     * @param dataType the value for t_article_info.data_type
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_info.content
     *
     * @return the value of t_article_info.content
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_info.content
     *
     * @param content the value for t_article_info.content
     *
     * @mbggenerated Tue Apr 17 22:38:35 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    public UserInfo getCreate() {
        return create;
    }

    public void setCreate(UserInfo create) {
        this.create = create;
    }

    public UserInfo getEdit() {
        return edit;
    }

    public void setEdit(UserInfo edit) {
        this.edit = edit;
    }

    public UploadFile getCover() {
        return cover;
    }

    public void setCover(UploadFile cover) {
        this.cover = cover;
    }

    public ArticleClass getArticleClass() {
        return articleClass;
    }

    public void setArticleClass(ArticleClass articleClass) {
        this.articleClass = articleClass;
    }
}