package com.example.project.model;

import java.util.Date;

public class FriendLink {

    private UserInfo create;

    private UserInfo edit;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.link
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_link.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date editDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.id
     *
     * @return the value of t_friend_link.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.id
     *
     * @param id the value for t_friend_link.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.link
     *
     * @return the value of t_friend_link.link
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.link
     *
     * @param link the value for t_friend_link.link
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.name
     *
     * @return the value of t_friend_link.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.name
     *
     * @param name the value for t_friend_link.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.create_user_id
     *
     * @return the value of t_friend_link.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.create_user_id
     *
     * @param createUserId the value for t_friend_link.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.create_date
     *
     * @return the value of t_friend_link.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.create_date
     *
     * @param createDate the value for t_friend_link.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.edit_user_id
     *
     * @return the value of t_friend_link.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.edit_user_id
     *
     * @param editUserId the value for t_friend_link.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_link.edit_date
     *
     * @return the value of t_friend_link.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_link.edit_date
     *
     * @param editDate the value for t_friend_link.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    public UserInfo getCreate() {
        return create;
    }

    public void setCreate(UserInfo create) {
        this.create = create;
    }

    public UserInfo getEdit() {
        return edit;
    }

    public void setEdit(UserInfo edit) {
        this.edit = edit;
    }
}