package com.example.project.model;

import java.util.Date;

public class LeaveWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.title
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.qq
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave_word.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.id
     *
     * @return the value of t_leave_word.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.id
     *
     * @param id the value for t_leave_word.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.title
     *
     * @return the value of t_leave_word.title
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.title
     *
     * @param title the value for t_leave_word.title
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.content
     *
     * @return the value of t_leave_word.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.content
     *
     * @param content the value for t_leave_word.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.name
     *
     * @return the value of t_leave_word.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.name
     *
     * @param name the value for t_leave_word.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.phone
     *
     * @return the value of t_leave_word.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.phone
     *
     * @param phone the value for t_leave_word.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.qq
     *
     * @return the value of t_leave_word.qq
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.qq
     *
     * @param qq the value for t_leave_word.qq
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave_word.create_date
     *
     * @return the value of t_leave_word.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave_word.create_date
     *
     * @param createDate the value for t_leave_word.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}