package com.example.project.model;

import java.util.List;

public class Menu {

    private List<Menu> childMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.name
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.parent_id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.host_path
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private String hostPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.remark
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.sort
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.name
     *
     * @return the value of t_menu.name
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.name
     *
     * @param name the value for t_menu.name
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.parent_id
     *
     * @return the value of t_menu.parent_id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.parent_id
     *
     * @param parentId the value for t_menu.parent_id
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.host_path
     *
     * @return the value of t_menu.host_path
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public String getHostPath() {
        return hostPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.host_path
     *
     * @param hostPath the value for t_menu.host_path
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setHostPath(String hostPath) {
        this.hostPath = hostPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.remark
     *
     * @return the value of t_menu.remark
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.remark
     *
     * @param remark the value for t_menu.remark
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.sort
     *
     * @return the value of t_menu.sort
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.sort
     *
     * @param sort the value for t_menu.sort
     *
     * @mbggenerated Fri Sep 22 15:45:34 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public List<Menu> getChildMenu() {
        return childMenu;
    }

    public void setChildMenu(List<Menu> childMenu) {
        this.childMenu = childMenu;
    }
}