package com.example.project.model;

import java.util.Date;

public class ProjectConfig {

    private UserInfo create;

    private UserInfo edit;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.address
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.email
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_config.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    private Date editDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.id
     *
     * @return the value of t_project_config.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.id
     *
     * @param id the value for t_project_config.id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.name
     *
     * @return the value of t_project_config.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.name
     *
     * @param name the value for t_project_config.name
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.address
     *
     * @return the value of t_project_config.address
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.address
     *
     * @param address the value for t_project_config.address
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.phone
     *
     * @return the value of t_project_config.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.phone
     *
     * @param phone the value for t_project_config.phone
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.email
     *
     * @return the value of t_project_config.email
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.email
     *
     * @param email the value for t_project_config.email
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.content
     *
     * @return the value of t_project_config.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.content
     *
     * @param content the value for t_project_config.content
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.create_user_id
     *
     * @return the value of t_project_config.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.create_user_id
     *
     * @param createUserId the value for t_project_config.create_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.create_date
     *
     * @return the value of t_project_config.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.create_date
     *
     * @param createDate the value for t_project_config.create_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.edit_user_id
     *
     * @return the value of t_project_config.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.edit_user_id
     *
     * @param editUserId the value for t_project_config.edit_user_id
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_config.edit_date
     *
     * @return the value of t_project_config.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_config.edit_date
     *
     * @param editDate the value for t_project_config.edit_date
     *
     * @mbggenerated Wed Apr 18 00:53:15 CST 2018
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    public UserInfo getCreate() {
        return create;
    }

    public void setCreate(UserInfo create) {
        this.create = create;
    }

    public UserInfo getEdit() {
        return edit;
    }

    public void setEdit(UserInfo edit) {
        this.edit = edit;
    }
}