package com.example.project.model;

import java.util.Date;

public class UploadFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.file_type
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.file_path
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.file_size
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.file_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upload_file.create_date
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.id
     *
     * @return the value of t_upload_file.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.id
     *
     * @param id the value for t_upload_file.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.file_type
     *
     * @return the value of t_upload_file.file_type
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.file_type
     *
     * @param fileType the value for t_upload_file.file_type
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.file_path
     *
     * @return the value of t_upload_file.file_path
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.file_path
     *
     * @param filePath the value for t_upload_file.file_path
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.file_size
     *
     * @return the value of t_upload_file.file_size
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.file_size
     *
     * @param fileSize the value for t_upload_file.file_size
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.file_name
     *
     * @return the value of t_upload_file.file_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.file_name
     *
     * @param fileName the value for t_upload_file.file_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upload_file.create_date
     *
     * @return the value of t_upload_file.create_date
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upload_file.create_date
     *
     * @param createDate the value for t_upload_file.create_date
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}