package com.example.project.model;

public class UserInfo {
	
	 /**
     * 关联头像
     */
    private UploadFile icon;

    /**
     * 关联角色
     */
    private Role role;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.role_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.login_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.phone_num
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.e_mail
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.password
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.img_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.sex
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.status
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.id
     *
     * @return the value of t_userinfo.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.id
     *
     * @param id the value for t_userinfo.id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.role_id
     *
     * @return the value of t_userinfo.role_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.role_id
     *
     * @param roleId the value for t_userinfo.role_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.name
     *
     * @return the value of t_userinfo.name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.name
     *
     * @param name the value for t_userinfo.name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.login_name
     *
     * @return the value of t_userinfo.login_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.login_name
     *
     * @param loginName the value for t_userinfo.login_name
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.phone_num
     *
     * @return the value of t_userinfo.phone_num
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.phone_num
     *
     * @param phoneNum the value for t_userinfo.phone_num
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.e_mail
     *
     * @return the value of t_userinfo.e_mail
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.e_mail
     *
     * @param eMail the value for t_userinfo.e_mail
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.password
     *
     * @return the value of t_userinfo.password
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.password
     *
     * @param password the value for t_userinfo.password
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.img_id
     *
     * @return the value of t_userinfo.img_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.img_id
     *
     * @param imgId the value for t_userinfo.img_id
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.sex
     *
     * @return the value of t_userinfo.sex
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.sex
     *
     * @param sex the value for t_userinfo.sex
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.status
     *
     * @return the value of t_userinfo.status
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.status
     *
     * @param status the value for t_userinfo.status
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
    
    public UploadFile getIcon() {
        return icon;
    }

    public void setIcon(UploadFile icon) {
        this.icon = icon;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}