package com.example.project.mapper;

import com.example.project.model.AboutUs;
import com.example.project.model.AboutUsExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AboutUsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int countByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insert(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insertSelective(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    List<AboutUs> selectByExampleWithBLOBs(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    List<AboutUs> selectByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    AboutUs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") AboutUs record, @Param("example") AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AboutUs record, @Param("example") AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExample(@Param("record") AboutUs record, @Param("example") AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKeySelective(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_about_us
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKey(AboutUs record);
}