package com.example.project.mapper;


import com.example.project.model.ArticleInfo;
import com.example.project.model.ArticleInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int countByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int deleteByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int insert(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int insertSelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    List<ArticleInfo> selectByExampleWithBLOBs(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    List<ArticleInfo> selectByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    ArticleInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByExample(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByPrimaryKeySelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_info
     *
     * @mbggenerated Thu Oct 26 11:26:30 CST 2017
     */
    int updateByPrimaryKey(ArticleInfo record);
}