package com.example.project.mapper;

import com.example.project.model.LeaveWord;
import com.example.project.model.LeaveWordExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface LeaveWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int countByExample(LeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByExample(LeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insert(LeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insertSelective(LeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    List<LeaveWord> selectByExample(LeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    LeaveWord selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") LeaveWord record, @Param("example") LeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExample(@Param("record") LeaveWord record, @Param("example") LeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKeySelective(LeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave_word
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKey(LeaveWord record);
}