package com.example.project.mapper;

import com.example.project.model.ProjectConfig;
import com.example.project.model.ProjectConfigExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ProjectConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int countByExample(ProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByExample(ProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insert(ProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int insertSelective(ProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    List<ProjectConfig> selectByExample(ProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    ProjectConfig selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjectConfig record, @Param("example") ProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByExample(@Param("record") ProjectConfig record, @Param("example") ProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_config
     *
     * @mbggenerated Wed Apr 18 00:01:35 CST 2018
     */
    int updateByPrimaryKey(ProjectConfig record);
}