package com.example.project.mapper;

import com.example.project.model.UploadFile;
import com.example.project.model.UploadFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UploadFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int countByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int deleteByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int insert(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int insertSelective(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    List<UploadFile> selectByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    UploadFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int updateByExample(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int updateByPrimaryKeySelective(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_file
     *
     * @mbggenerated Mon Apr 16 11:12:44 CST 2018
     */
    int updateByPrimaryKey(UploadFile record);
}